/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ubxgniddkylbwuuesbbi"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVieGduaWRka3lsYnd1dWVzYmJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNTIxNTYsImV4cCI6MjA3MzkyODE1Nn0.A-FL9ogOU-JYeeoYzg3YwVjlyIdzEXttX-DdNlbYfG4"